language: go

go:
  - 1.6

before_install:
  - go get github.com/mitchellh/gox

script:
  # build test for supported platforms
  - gox -os="linux"
  - gox -os="darwin"
  - gox -os="freebsd"

  # run tests on a standard platform
  - go test -v ./...
